version: "3"
services:
  database:
    image: "recipe-forge-database"
    build:
      context: ./backend
      dockerfile: ./src/docker/Dockerfile.database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "recipe_forge"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    image: "recipe-forge-backend"
    build:
      context: ./backend
      dockerfile: ./src/docker/Dockerfile.backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    depends_on:
      - database

  frontend:
    image: "recipe-forge-frontend"
    build:
      context: ./frontend
      dockerfile: ./src/docker/Dockerfile.frontend
    ports:
      - "4321:4321"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

volumes:
  db_data:
  backend:
  frontend: